// This file is generated by Slice Machine. Update with care!

import FooterCopyright from './FooterCopyright';
import FooterLinks from './FooterLinks';
import HeroBanner from './HeroBanner';
import Imprint from './Imprint';
import SocialMediaIcons from './SocialMediaIcons';
import Terms from './Terms';

export {
	FooterCopyright,
	FooterLinks,
	HeroBanner,
	Imprint,
	SocialMediaIcons,
	Terms,
};

export const components = {
	footer_copyright: FooterCopyright,
	footer_links: FooterLinks,
	hero_banner: HeroBanner,
	imprint: Imprint,
	social_media_icons: SocialMediaIcons,
	terms: Terms,
};
